export enum ServicesType {
  HAEMODIALYSIS = 'HAEMODIALYSIS',
  MEDICATION = 'MEDICATION',
  VACCINATION = 'VACCINATION',
  LAB_ORDER = 'LAB_ORDER',
  DOCTOR_NEPHROLOGIST_REVIEW = 'DOCTOR_NEPHROLOGIST_REVIEW',
  DOCTOR_PIC_REVIEW = 'DOCTOR_PIC_REVIEW',
}
